// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqsKmldeihmKk-zYHCZZBahF1TOdKYTUw',
    appId: '1:737210866140:web:163ff9c13e42c12fbf9719',
    messagingSenderId: '737210866140',
    projectId: 'mychatapp-1fe1e',
    authDomain: 'mychatapp-1fe1e.firebaseapp.com',
    storageBucket: 'mychatapp-1fe1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKaYGMNQKovbKY6FwttcI69do2Wxj4ZUU',
    appId: '1:737210866140:android:6d1b8ccb84b9146cbf9719',
    messagingSenderId: '737210866140',
    projectId: 'mychatapp-1fe1e',
    storageBucket: 'mychatapp-1fe1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd7Y_CEIplu55kD4jiCrwJ6sVmntBvAuQ',
    appId: '1:737210866140:ios:022e4d73e63dcce7bf9719',
    messagingSenderId: '737210866140',
    projectId: 'mychatapp-1fe1e',
    storageBucket: 'mychatapp-1fe1e.firebasestorage.app',
    iosBundleId: 'com.example.firbaseprojet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd7Y_CEIplu55kD4jiCrwJ6sVmntBvAuQ',
    appId: '1:737210866140:ios:022e4d73e63dcce7bf9719',
    messagingSenderId: '737210866140',
    projectId: 'mychatapp-1fe1e',
    storageBucket: 'mychatapp-1fe1e.firebasestorage.app',
    iosBundleId: 'com.example.firbaseprojet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqsKmldeihmKk-zYHCZZBahF1TOdKYTUw',
    appId: '1:737210866140:web:32c7a09a8fd85f4fbf9719',
    messagingSenderId: '737210866140',
    projectId: 'mychatapp-1fe1e',
    authDomain: 'mychatapp-1fe1e.firebaseapp.com',
    storageBucket: 'mychatapp-1fe1e.firebasestorage.app',
  );

}